name: Build Sphinx documentation

on:
  push:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: "ubuntu-latest"

    steps:
        - name: Set up Python 3.12.3
          uses: actions/setup-python@v4
          with:
            python-version: "3.12.3"

        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r docs/requirements.txt

        - name: Build documentation
          run: |
            sphinx-build docs docs/_build

        - name: Upload documentation
          uses: actions/upload-artifact@v4
          with:
            name: sphinx-docs
            path: docs/_build
